In [ ]:
import numpy as np

In [ ]:
# creating 1D array
arr_1d=[12,202,303]

In [ ]:
arr_1d

[12, 202, 303]

In [ ]:
# creating 2 D array
arr_2d=([12,202,303],[78,68,90])

In [ ]:
arr_2d

([12, 202, 303], [78, 68, 90])

In [ ]:
arr1=np.array(arr_2d)

In [ ]:
arr1

array([[ 12, 202, 303],
       [ 78,  68,  90]])

In [ ]:
# Array attributes


In [ ]:
# ndim
arr1.ndim

2

In [ ]:
# shape
arr1.shape

(2, 3)

In [ ]:
# size
arr1.size

6

In [ ]:
# dtype
arr1.dtype

dtype('int64')

In [ ]:
# item size
arr1.item

<function ndarray.item>

In [ ]:
# Array creation methods


In [ ]:
# arange
arr=np.arange(1,50)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
# np.linspace
arr1=np.linspace(25,50,50)

In [ ]:
arr1

array([25.        , 25.51020408, 26.02040816, 26.53061224, 27.04081633,
       27.55102041, 28.06122449, 28.57142857, 29.08163265, 29.59183673,
       30.10204082, 30.6122449 , 31.12244898, 31.63265306, 32.14285714,
       32.65306122, 33.16326531, 33.67346939, 34.18367347, 34.69387755,
       35.20408163, 35.71428571, 36.2244898 , 36.73469388, 37.24489796,
       37.75510204, 38.26530612, 38.7755102 , 39.28571429, 39.79591837,
       40.30612245, 40.81632653, 41.32653061, 41.83673469, 42.34693878,
       42.85714286, 43.36734694, 43.87755102, 44.3877551 , 44.89795918,
       45.40816327, 45.91836735, 46.42857143, 46.93877551, 47.44897959,
       47.95918367, 48.46938776, 48.97959184, 49.48979592, 50.        ])

In [ ]:
# zeroes 1 D
arr2=np.zeros(5)

In [ ]:
arr2

array([0., 0., 0., 0., 0.])

In [ ]:
# 2 da rray
arr2=np.zeros((5,6))

In [ ]:
arr2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
# # d array
arr2=np.zeros((5,6,6))

In [ ]:
arr2

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
      

In [ ]:
# ones 1 d array
arr=np.ones(5)

In [ ]:
arr

array([1., 1., 1., 1., 1.])

In [ ]:
# 2 d array
arr=np.ones((5,6),dtype=complex)

In [ ]:
arr

array([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]])

In [ ]:
# 3 d array
arr=np.ones((5,6,2),dtype=complex)

In [ ]:
arr

array([[[1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j]],

       [[1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j]],

       [[1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j]],

       [[1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j]],

       [[1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j]]])

In [ ]:
# full 2 D array
arr=np.full((5,6),200)

In [ ]:
arr

array([[200, 200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200, 200]])

In [ ]:
# full 3 D array
arr=np.full((4,5,6),500)

In [ ]:
arr

array([[[500, 500, 500, 500, 500, 500],
        [500, 500, 500, 500, 500, 500],
        [500, 500, 500, 500, 500, 500],
        [500, 500, 500, 500, 500, 500],
        [500, 500, 500, 500, 500, 500]],

       [[500, 500, 500, 500, 500, 500],
        [500, 500, 500, 500, 500, 500],
        [500, 500, 500, 500, 500, 500],
        [500, 500, 500, 500, 500, 500],
        [500, 500, 500, 500, 500, 500]],

       [[500, 500, 500, 500, 500, 500],
        [500, 500, 500, 500, 500, 500],
        [500, 500, 500, 500, 500, 500],
        [500, 500, 500, 500, 500, 500],
        [500, 500, 500, 500, 500, 500]],

       [[500, 500, 500, 500, 500, 500],
        [500, 500, 500, 500, 500, 500],
        [500, 500, 500, 500, 500, 500],
        [500, 500, 500, 500, 500, 500],
        [500, 500, 500, 500, 500, 500]]])

In [ ]:
# empty 1 D array
arr=np.empty(3)
arr
# same for 2 and 3 d array

array([0. , 0.5, 1. ])

In [ ]:
# identity
arr=np.identity(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# eye
arr=np.eye(5,6,0,dtype=int)
arr

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0]])

In [ ]:
# Array manipulation

In [ ]:
a=np.array([1,2,3,4])

In [ ]:
# as typeea
a.astype(complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [ ]:
# repeat
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [ ]:
# transpose
np.transpose(a)

array([1, 2, 3, 4])

In [ ]:
arr2 = np.array([[1, 2, 2, 4],
                 [4, 5, 6, 7]])

In [ ]:
arr2

array([[1, 2, 2, 4],
       [4, 5, 6, 7]])

In [ ]:
# Transpose
arr2.T

array([[1, 4],
       [2, 5],
       [2, 6],
       [4, 7]])

In [ ]:
# flip
np.flip(arr2)

array([[7, 6, 5, 4],
       [4, 2, 2, 1]])

In [ ]:
# delete
np.delete(arr2,4)

array([1, 2, 2, 4, 5, 6, 7])

In [ ]:
# unique
np.unique(arr2)

array([1, 2, 4, 5, 6, 7])

In [ ]:
# concatenate
a1=np.array([1,2,3,4,5])
a2=np.array([5,6,7,8,9])
arr=np.concatenate((a1,a2))

In [ ]:
arr

array([1, 2, 3, 4, 5, 5, 6, 7, 8, 9])

In [ ]:
# coulmn concatenate
import numpy as np

a1 = np.array([[1, 2],
               [3, 4]])

a2 = np.array([[5, 6],
               [7, 8]])

arr = np.concatenate((a1, a2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Stack
arr1 = np.arange(1,11).reshape(2,5)
arr2 = np.arange(11,21).reshape(2,5)


In [ ]:
np.stack((arr1,arr2))

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [ ]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [ ]:
# split
np.split(arr,2)

[array([[1, 2, 5, 6]]), array([[3, 4, 7, 8]])]

In [ ]:
np.hsplit(arr,3)

ValueError: array split does not result in an equal division

In [ ]:
# Random

In [ ]:
import random

In [ ]:
np.random.randint(1,15)

6

In [ ]:
np.random.rand(2,5)

array([[0.41585834, 0.21914925, 0.06896859, 0.78693256, 0.89629655],
       [0.88326791, 0.19401922, 0.79267263, 0.76932229, 0.52889683]])

In [ ]:
np.random.randn(5,7)

array([[ 1.91245196, -1.31506001, -0.63992144, -0.43435241,  0.13868264,
        -0.37219906,  0.84862513],
       [-0.15564699,  2.16793002,  0.72955779, -1.09370372,  2.34960213,
         1.65234562, -0.21001651],
       [ 1.00750135,  1.20983763,  0.15536184,  0.08304523, -0.67803696,
         1.40706943, -0.15770859],
       [-0.2222479 ,  1.15025501,  0.15849529, -0.57627815,  0.00758692,
         0.1469293 ,  0.39337486],
       [ 0.61301219, -0.60055576,  0.12509399,  0.19335354, -1.20122856,
        -1.58109192,  0.6363176 ]])

In [ ]:
np.random.choice([12,2,3,4,5,5])

np.int64(3)

In [ ]:
# indexing aand slicing


In [ ]:
# 2d indexing
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print(arr)


[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
print(arr[0,0])   # 10
print(arr[0,2])   # 30
print(arr[1,1])   # 50
print(arr[2,0])   # 70
print(arr[2,2])   # 90

10
30
50
70
90


In [ ]:
print(arr[0:2,1:3])

[[20 30]
 [50 60]]


In [ ]:
# 3d array indeinx
arr = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
print(arr[:,:,1])

[[ 2  5]
 [ 8 11]]


In [ ]:
# all
a = np.array([-4,56,-6,78,654,-90,67,89,54,34])

In [ ]:
a.all()

np.True_

In [ ]:
# any
a.any()

np.True_

In [ ]:
# where
np.where(a<0)

(array([0, 2, 5]),)

In [ ]:
# array opeartions


In [ ]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

B = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9,  10, 11, 12],
              [13, 14, 15, 16]])

T = np.arange(1, 25).reshape(2, 3, 4)

In [ ]:
arr = np.array([45,65,23,78,90,23,34,45])

In [ ]:
arr

array([45, 65, 23, 78, 90, 23, 34, 45])

In [ ]:
print(arr)

[45 65 23 78 90 23 34 45]


In [ ]:
np.sort(arr)

array([23, 23, 34, 45, 45, 65, 78, 90])

In [ ]:
np.argsort(arr)

array([2, 5, 6, 0, 7, 1, 3, 4])

In [ ]:
np.max(arr)

np.int64(90)

In [ ]:
np.argmax(arr)

np.int64(4)

In [ ]:
np.min(arr)

np.int64(23)

In [ ]:
np.argmin(arr)

np.int64(2)

In [ ]:
np.sum(arr)

np.int64(403)

In [ ]:
# dot operator
arr1
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
arr = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)

In [ ]:
arr * arr2

array([[ 5, 12],
       [21, 32]])

In [ ]:
np.dot(arr,arr2)

array([[19, 22],
       [43, 50]])

In [ ]:
arr @ arr2

array([[19, 22],
       [43, 50]])

In [ ]:
np.prod(arr2)

np.int64(1680)

In [ ]:
np.sqrt(arr)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [ ]:
np.var(arr)

np.float64(1.25)

In [ ]:
np.sqrt(200)

np.float64(14.142135623730951)

In [ ]:
np.std(arr)

np.float64(1.118033988749895)